sudo: required
services:
  - docker

before_install:
  - docker build -t KalyankarRajesh/docker-react -f Dockerfile.dev .

script:
  - docker run KalyankarRajesh/docker-react npm run test -- --coverage



