sudo: required
services:
  - docker

before_install:
  - docker build -t kalyankarrajesh/docker-react -f Dockerfile.dev .

script:
  - docker run kalyankarrajesh/docker-react npm run test -- --coverage
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "dockertest"
  env: "Dockertest-env"
  bucket_name: "elasticbeanstalk-us-west-1-951492606668"
  bucket_path: "dockertest"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  



